services:
  swu:
    container_name: swu
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - "swu:latest" 
    ports:
      - ${DOCKER_BIND_ADDR}:${DOCKER_PORT}:8000
    volumes:
      - ${DOCKER_LOCAL_PATH}:/data
      - ${WEB_ROOT}:${WEB_ROOT}