FROM python:3.10

WORKDIR /app

ADD docker-run.sh /app/
ADD .env /app/
ADD requirements.txt /app/
ADD main.py /app/
ADD utils/ /app/
ADD gunicorn_config.py /app/

RUN python -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt

EXPOSE 8000

ENTRYPOINT [ "./venv/bin/gunicorn", "--config", "gunicorn_config.py", "-b", "0.0.0.0:8000", "'main:app'" ]